default_platform(:ios)

platform :ios do
  lane :beta do
    get_certificates
    get_provisioning_profile
    increment_build_number
    build_app(scheme: "English")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
