default_platform(:ios)

platform :ios do
  lane :beta do
    get_certificates
    get_provisioning_profile

    ensure_git_status_clean
    increment_build_number
    commit_version_bump
    add_git_tag
    push_to_git_remote

    build_app(scheme: "English")

    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  lane :upload_symbols do
    download_dsyms
    upload_symbols_to_sentry(
      auth_token: 'eedd2923210442a5b8097dbd425daa482e834c68ced4408792f581209ce1886f',
      org_slug: 'takesafe',
      project_slug: 'ios',
    )
  end
end
