default_platform(:ios)

platform :ios do
  lane :beta do
    get_certificates
    get_provisioning_profile

    ensure_git_status_clean
    increment_build_number(
      build_number: latest_testflight_build_number + 1
    )
    commit_version_bump
    add_git_tag
    push_to_git_remote

    build_app(scheme: "English")

    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
