name: CD

on:
  push:
    branches:
      - dev

jobs:
  upload_to_testflight:
    name: Upload to TestFlight
    
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1

      - run: bundle install
