name: CD

on:
  push:
    branches:
      - dev

jobs:
  fastlane:
    name: Fastlane
    
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: beta
